package com.razumly.mvp.eventMap

import androidx.compose.ui.unit.dp

internal val MAP_ACTION_BUTTON_NAV_PADDING = 32.dp
internal val MAP_ACTION_BUTTON_EXTRA_DOWN_OFFSET = 10.dp
internal val MAP_ACTION_BUTTON_SCAFFOLD_BOTTOM_SPACING = 16.dp
internal val MAP_CLOSE_BUTTON_EXTRA_BOTTOM_PADDING =
    MAP_ACTION_BUTTON_NAV_PADDING + MAP_ACTION_BUTTON_EXTRA_DOWN_OFFSET + MAP_ACTION_BUTTON_SCAFFOLD_BOTTOM_SPACING
